version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      - POSTGRES_DB=zapier
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  primary-backend:
    build: ./primary-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@my_postgres:5432/zapier"
      KAFKA_BROKER: "kafka:9092"

  hooks:
    build: ./hooks
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@my_postgres:5432/zapier"
      KAFKA_BROKER: "kafka:9092"

  processor:
    build: ./processor
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@my_postgres:5432/zapier"
      KAFKA_BROKER: "kafka:9092"

  worker:
    build: ./worker
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@my_postgres:5432/zapier"
      KAFKA_BROKER: "kafka:9092"

  client:
    build: ./client
    ports:
      - "3004:3004"
    environment:
      API_BASE_URL: "http://primary-backend:3000"
      KAFKA_BROKER: "kafka:9092"

volumes:
  db_data:
  kafka_data: